// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { cometChatBlock } from ".";
import { auth } from "./auth";

export const cometChatBlockSchema = parseBlockSchema(cometChatBlock);
export const cometChatCredentialsSchema = parseBlockCredentials(
  cometChatBlock.id,
  auth.schema,
);
