// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { cometchatBlock } from ".";
import { auth } from "./auth";

export const cometchatBlockSchema = parseBlockSchema(cometchatBlock);
export const cometchatCredentialsSchema = parseBlockCredentials(
  cometchatBlock.id,
  auth.schema,
);
